# Generated by Django 5.2.6 on 2025-09-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bola',
        ),
    ]
